/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentDTO } from './commentDTO';


export interface PostDTO { 
    id?: number;
    postTitle?: string;
    postText?: string;
    subScapeName?: string;
    creatorUsername?: string;
    comments?: Array<CommentDTO>;
    createdAt?: string;
    modifiedAt?: string;
}

