/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubScapeDTO { 
    id?: number;
    subScapeName?: string;
    subScapeDescription?: string;
    creatorUsername?: string;
}

